export const cv = {
  data: {
    name: {
      raw: 'Waqar Haider',
      first: 'Waqar',
      last: 'Haider',
      middle: '',
      title: '',
    },
    phoneNumbers: ['+923082668002'],
    websites: ['linkedin.com/in/waqar-haider-'],
    emails: ['k191523@nu.edu.pk'],
    dateOfBirth: null,
    location: {
      formatted: 'Karachi, Karachi City, Sindh, Pakistan',
      postalCode: null,
      state: 'Sindh',
      country: 'Pakistan',
      countryCode: 'PK',
      rawInput: 'Karachi, Pakistan',
      streetNumber: null,
      street: null,
      apartmentNumber: null,
      city: 'Karachi',
      latitude: { $numberDouble: '24.8607343' },
      longitude: { $numberDouble: '67.0011364' },
    },
    objective:
      'To secure a challenging and dynamic role in the computer science industry that pull my technical skills and expertise, while also providing opportunities for professional growth and development. I am seeking a role that allows me to work and collaborate with talented professionals and contribute to the development of innovative solutions.',
    languages: ['English'],
    summary: '',
    totalYearsExperience: { $numberInt: '0' },
    headShot: null,
    // tab
    education: [
      {
        id: { $numberInt: '15367856' },
        organization: 'National University of Emerging Sciences',
        accreditation: {
          education: 'Bachelor of Computer Science (currently studying)',
          inputStr: 'Bachelor of Computer Science (currently studying)',
          matchStr: '',
          educationLevel: 'bachelors',
        },
        grade: null,
        location: {
          formatted: 'Karachi, Karachi City, Sindh, Pakistan',
          postalCode: null,
          state: 'Sindh',
          country: 'Pakistan',
          countryCode: 'PK',
          rawInput: 'Karachi, Pakistan',
          streetNumber: null,
          street: null,
          apartmentNumber: null,
          city: 'Karachi',
          latitude: { $numberDouble: '24.8607343' },
          longitude: { $numberDouble: '67.0011364' },
        },
        dates: {
          completionDate: { $date: { $numberLong: '1685577600000' } },
          isCurrent: true,
          startDate: { $date: { $numberLong: '1546300800000' } },
        },
      },
      {
        id: { $numberInt: '15367857' },
        organization: 'The Citizen Foundation College',
        accreditation: {
          education: 'Intermediate',
          inputStr: 'Intermediate in Engineering',
          matchStr: '',
          educationLevel: 'school',
        },
        grade: null,
        location: {
          formatted: 'Karachi, Karachi City, Sindh, Pakistan',
          postalCode: null,
          state: 'Sindh',
          country: 'Pakistan',
          countryCode: 'PK',
          rawInput: 'Karachi, Pakistan',
          streetNumber: null,
          street: null,
          apartmentNumber: null,
          city: 'Karachi',
          latitude: { $numberDouble: '24.8607343' },
          longitude: { $numberDouble: '67.0011364' },
        },
        dates: {
          completionDate: { $date: { $numberLong: '1575158400000' } },
          isCurrent: false,
          startDate: { $date: { $numberLong: '1483228800000' } },
        },
      },
      {
        id: { $numberInt: '15367858' },
        organization: 'THE CITIZEN FOUNDATION SCHOOL',
        accreditation: {
          education: 'Matriculation in Science',
          inputStr: 'Matriculation in Science',
          matchStr: '',
          educationLevel: null,
        },
        grade: null,
        location: {
          formatted: 'Karachi, Karachi City, Sindh, Pakistan',
          postalCode: null,
          state: 'Sindh',
          country: 'Pakistan',
          countryCode: 'PK',
          rawInput: 'Karachi, Pakistan',
          streetNumber: null,
          street: null,
          apartmentNumber: null,
          city: 'Karachi',
          latitude: { $numberDouble: '24.8607343' },
          longitude: { $numberDouble: '67.0011364' },
        },
        dates: null,
      },
    ],

    profession: null,
    linkedin: 'linkedin.com/in/waqar-haider-',
    // tab
    workExperience: [],
    // tab
    skills: [
      {
        id: { $numberInt: '159126231' },
        emsUniversityiId: 'KS122556LMQ829GZCCRV',
        name: 'Communications',
        lastUsed: null,
        numberOfMonths: null,
        type: 'soft_skill',
        sources: [
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126233' },
        emsiId: 'KS126QY605N7YVHFYCTW',
        name: 'MySQL',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
          { section: 'Projects', position: null, workExperienceId: null },
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126234' },
        emsiId: 'ESA0C585B3CBA1045AD0',
        name: 'MERN Stack',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
        ],
      },
      {
        id: { $numberInt: '159126235' },
        emsiId: 'KS440SJ73G5RZYMLVKV7',
        name: 'Source (Game Engine)',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126236' },
        emsiId: 'KS121F45VPV8C9W3QFYH',
        name: 'Cascading Style Sheets (CSS)',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
          {
            section: 'Achievements',
            position: null,
            workExperienceId: null,
          },
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
          { section: 'Projects', position: null, workExperienceId: null },
          {
            section: 'Achievements',
            position: null,
            workExperienceId: null,
          },
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126238' },
        emsiId: 'KS124JB619VXG6RQ810C',
        name: 'Leadership',
        lastUsed: null,
        numberOfMonths: null,
        type: 'soft_skill',
        sources: [
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126240' },
        emsiId: 'KSKJX44T33B6D4UCC8CB',
        name: 'Teamwork',
        lastUsed: null,
        numberOfMonths: null,
        type: 'soft_skill',
        sources: [
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126241' },
        emsiId: 'KS7YXWLEAKN8QOFDFVS2',
        name: 'Postman',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126242' },
        emsiId: 'KS120PQ6XD1JWMFQVJNW',
        name: 'Teaching',
        lastUsed: null,
        numberOfMonths: null,
        type: 'soft_skill',
        sources: [
          {
            section: 'Extracurriculars/Leadership',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126244' },
        emsiId: 'KS121DS6GB09TFN7RLX0',
        name: 'Career Development',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          {
            section: 'Achievements',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126245' },
        emsiId: 'KS1200771D9CR9LB4MWW',
        name: 'JavaScript (Programming Language)',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
          {
            section: 'Achievements',
            position: null,
            workExperienceId: null,
          },
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126248' },
        emsiId: 'KS1238H659P08Z726BK8',
        name: 'E-Commerce',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
        ],
      },
      {
        id: { $numberInt: '159126249' },
        emsiId: 'KS1200578T5QCYT0Z98G',
        name: 'HyperText Markup Language (HTML)',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
          {
            section: 'Achievements',
            position: null,
            workExperienceId: null,
          },
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
          { section: 'Projects', position: null, workExperienceId: null },
          {
            section: 'Achievements',
            position: null,
            workExperienceId: null,
          },
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126250' },
        emsiId: 'KS128866SHL94J005TTG',
        name: 'Quality Assurance',
        lastUsed: null,
        numberOfMonths: null,
        type: 'soft_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
        ],
      },
      {
        id: { $numberInt: '159126232' },
        emsiId: 'KS1226Y6DNDT05G7FJ4J',
        name: 'Computer Science',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Summary', position: null, workExperienceId: null },
        ],
      },
      {
        id: { $numberInt: '159126237' },
        emsiId: 'KS440W3640PNXPGB5MSW',
        name: 'Software Quality (SQA/SQC)',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
        ],
      },
      {
        id: { $numberInt: '159126239' },
        emsiId: 'KS6840J6LR0TLQ86LZJC',
        name: 'Front End (Software Engineering)',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
        ],
      },
      {
        id: { $numberInt: '159126243' },
        emsiId: 'KS122Z36QK3N5097B5JH',
        name: 'Web Development',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126246' },
        emsiId: 'KS1275Z6908VHW76FRXH',
        name: 'Object-Oriented Programming (OOP)',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
          {
            section: 'Extracurriculars/Leadership',
            position: null,
            workExperienceId: null,
          },
          {
            section: 'Skills/Interests/Languages',
            position: null,
            workExperienceId: null,
          },
          {
            section: 'Extracurriculars/Leadership',
            position: null,
            workExperienceId: null,
          },
        ],
      },
      {
        id: { $numberInt: '159126247' },
        emsiId: 'KS1245B69S835T6C8KB4',
        name: 'Functional Testing',
        lastUsed: null,
        numberOfMonths: null,
        type: 'hard_skill',
        sources: [
          { section: 'Projects', position: null, workExperienceId: null },
        ],
      },
    ],
    certifications: [
      'The Citizen Foundation College Qayumabad',
      'The Citizen Foundation School',
      'Assist in OOP course',
      'Programming Languages',
    ],
    publications: [],
    referees: [],
    sections: [
      {
        sectionType: 'PersonalDetails',
        bbox: [
          { $numberDouble: '32.31264' },
          { $numberDouble: '26.197327' },
          { $numberDouble: '173.73215' },
          { $numberDouble: '47.486267' },
        ],
        pageIndex: { $numberInt: '0' },
        text: 'Waqar Haider',
      },
      {
        sectionType: 'Summary',
        bbox: [
          { $numberDouble: '32.071682' },
          { $numberDouble: '59.361023' },
          { $numberDouble: '344.81332' },
          { $numberDouble: '133.68878' },
        ],
        pageIndex: { $numberInt: '0' },
        text:
          'OBJECTIVE To secure a challenging and dynamic role in the computer science industry that pull my technical skills and expertise, while also providing opportunities for professional growth and development. I am seeking a role that allows me to work and collaborate with talented professionals and contribute to the development of innovative solutions.',
      },
      {
        sectionType: 'Projects',
        bbox: [
          { $numberDouble: '39.646355' },
          { $numberDouble: '157.31104' },
          { $numberDouble: '314.9885' },
          { $numberDouble: '310.49725' },
        ],
        pageIndex: { $numberInt: '0' },
        text:
          'PROJECTS HIGHLIGHTS Photographic Website Blinker (MERN STACK) •Front end using React, Backend using NodeJS. Software Quality Assurance on FYP • Testing UI for glitches and consistency. • Functional testing of new modules. • Testing tech docs to be consistent with current application version. E-Commerce Website • Html, CSS, JavaScript, .NET, MySQL, 2021 • Customers add items to carts, give feedback, buy things.',
      },
      {
        sectionType: 'Education',
        bbox: [
          { $numberDouble: '38.803104' },
          { $numberDouble: '337.36102' },
          { $numberDouble: '344.6551' },
          { $numberDouble: '501.55624' },
        ],
        pageIndex: { $numberInt: '0' },
        text:
          'EDUCATION Bachelor of Computer Science (currently studying) National University OF Emerging Sciences 01/2019 - 6/2023, Karachi, Pakistan Intermediate in Engineering The Citizen Foundation College, Qayumabad 01/2017 - 12/2019, Karachi, Pakistan Matriculation in Science The Citizen Foundation School Karachi, Pakistan',
      },
      {
        sectionType: 'Extracurriculars/Leadership',
        bbox: [
          { $numberDouble: '34.81824' },
          { $numberDouble: '526.44806' },
          { $numberDouble: '159.34665' },
          { $numberDouble: '615.9342' },
        ],
        pageIndex: { $numberInt: '0' },
        text:
          'Experience •Teaching Assistant At FAST Assist in OOP course. •President in Society Think And Create.',
      },
      {
        sectionType: 'Achievements',
        bbox: [
          { $numberDouble: '38.9424' },
          { $numberDouble: '646.091' },
          { $numberDouble: '299.94193' },
          { $numberDouble: '711.3873' },
        ],
        pageIndex: { $numberInt: '0' },
        text:
          'ACHIEVEMENTS • Certificate on completion of HTML/CSS/JAVASCRIPT courses. • Participated in Coders Cup (speed programming competition). • Participated in Hackathon (speed programming competition). • Participated Theater Workshop. • Participated in Rahbar program (Career Development Program).',
      },
      {
        sectionType: 'PersonalDetails',
        bbox: [
          { $numberDouble: '445.20065' },
          { $numberDouble: '20.428345' },
          { $numberDouble: '569.86743' },
          { $numberDouble: '77.25159' },
        ],
        pageIndex: { $numberInt: '0' },
        text:
          'k191 523@nu.edu.pk 03082668002 Karachi, Pakistan linkedin.com/in/Waqar-Haider-',
      },
      {
        sectionType: 'Skills/Interests/Languages',
        bbox: [
          { $numberDouble: '419.63095' },
          { $numberDouble: '159.47101' },
          { $numberDouble: '546.0979' },
          { $numberDouble: '484.06717' },
        ],
        pageIndex: { $numberInt: '0' },
        text:
          'TECHNICAL SKILLS Frontend Development React. Web Development HTML, CSS, JavaScript. Testing Tools Postman, Jira. Programming Languages OOP,C++, C#. Databases MySQL, Oracle database. Source Code Versioning GitHub. SOFT SKILL Leadership Teamwork Communication',
      },
      {
        sectionType: 'Footer',
        bbox: [
          { $numberDouble: '559.838' },
          { $numberDouble: '817.843' },
          { $numberDouble: '571.1116' },
          { $numberDouble: '823.82263' },
        ],
        pageIndex: { $numberInt: '0' },
        text: '1/3',
      },
      {
        sectionType: 'Footer',
        bbox: [
          { $numberDouble: '558.42645' },
          { $numberDouble: '817.843' },
          { $numberDouble: '571.39557' },
          { $numberDouble: '823.82263' },
        ],
        pageIndex: { $numberInt: '1' },
        text: '2/3',
      },
    ],
    isResumeProbability: { $numberInt: '99' },
    rawText:
      'Waqar Haider\nOBJECTIVE To secure a challenging and dynamic role in the computer science industry that pull my technical skills and expertise, while also providing opportunities for professional growth and development. I am seeking a role that allows me to work and collaborate with talented professionals and contribute to the development of innovative solutions.\nPROJECTS HIGHLIGHTS Photographic Website Blinker (MERN STACK) •Front end using React, Backend using NodeJS. Software Quality Assurance on FYP • Testing UI for glitches and consistency. • Functional testing of new modules. • Testing tech docs to be consistent with current application version. E-Commerce Website • Html, CSS, JavaScript, .NET, MySQL, 2021 • Customers add items to carts, give feedback, buy things.\nEDUCATION Bachelor of Computer Science (currently studying) National University OF Emerging Sciences 01/2019 - 6/2023, Karachi, Pakistan Intermediate in Engineering The Citizen Foundation College, Qayumabad 01/2017 - 12/2019, Karachi, Pakistan Matriculation in Science The Citizen Foundation School Karachi, Pakistan\nExperience •Teaching Assistant At FAST Assist in OOP course. •President in Society Think And Create.\nACHIEVEMENTS • Certificate on completion of HTML/CSS/JAVASCRIPT courses. • Participated in Coders Cup (speed programming competition). • Participated in Hackathon (speed programming competition). • Participated Theater Workshop. • Participated in Rahbar program (Career Development Program).\nk191 523@nu.edu.pk 03082668002 Karachi, Pakistan linkedin.com/in/Waqar-Haider-\nTECHNICAL SKILLS Frontend Development React. Web Development HTML, CSS, JavaScript. Testing Tools Postman, Jira. Programming Languages OOP,C++, C#. Databases MySQL, Oracle database. Source Code Versioning GitHub. SOFT SKILL Leadership Teamwork Communication\n1/3\n2/3',
    redactedText:
      '***** ******\nOBJECTIVE To secure a challenging and dynamic role in the computer science industry that pull my technical skills and expertise, while also providing opportunities for professional growth and development. I am seeking a role that allows me to work and collaborate with talented professionals and contribute to the development of innovative solutions.\nPROJECTS HIGHLIGHTS Photographic Website Blinker (MERN STACK) •Front end using React, Backend using NodeJS. Software Quality Assurance on FYP • Testing UI for glitches and consistency. • Functional testing of new modules. • Testing tech docs to be consistent with current application version. E-Commerce Website • Html, CSS, JavaScript, .NET, MySQL* **** • Customers add items to carts, give feedback, buy things.\nEDUCATION Bachelor of Computer Science (currently studying) National University OF Emerging Sciences ******* * ******* ******** ******** Intermediate in Engineering The Citizen Foundation College, ********* ******* * ******** ******** ******** Matriculation in Science The Citizen Foundation School ******** ********\nExperience •Teaching Assistant At FAST Assist in OOP course. •President in Society Think And Create.\nACHIEVEMENTS • Certificate on completion of HTML/CSS/JAVASCRIPT courses. • Participated in Coders Cup (speed programming competition). • Participated in Hackathon (speed programming competition). • Participated Theater Workshop. • Participated in Rahbar program (Career Development Program).\nk191 ************* *********** ******** ******** *****************************\nTECHNICAL SKILLS Frontend Development React. Web Development HTML, CSS, JavaScript. Testing Tools Postman, Jira. Programming Languages OOP,C++, C#. Databases MySQL, Oracle database. Source Code Versioning GitHub. SOFT SKILL Leadership Teamwork Communication\n***\n***',
  },
  meta: {
    identifier: 'HthomWfH',
    fileName: 'd56449dbe64f41dfc8c5ea8223ca33b4',
    ready: true,
    readyDt: { $date: { $numberLong: '1678303792014' } },
    failed: false,
    expiryTime: null,
    language: 'en',
    pdf: 'http://api.affinda.com/v2/resumes',
    parentDocument: null,
    childDocuments: [],
    pages: [
      {
        id: { $numberInt: '14579071' },
        pageIndex: { $numberInt: '0' },
        image: null,
        height: { $numberDouble: '841.9200439453125' },
        width: { $numberDouble: '594.9600219726562' },
        rotation: { $numberInt: '0' },
      },
      {
        id: { $numberInt: '14579072' },
        pageIndex: { $numberInt: '1' },
        image: null,
        height: { $numberDouble: '841.9200439453125' },
        width: { $numberDouble: '594.9600219726562' },
        rotation: { $numberInt: '0' },
      },
    ],
    isVerified: true,
    reviewUrl: null,
    ocrConfidence: null,
    validatedDt: '2023-03-08T19:29:52.014516Z',
    exportedDt: null,
    isExported: false,
    createdDt: '2023-03-08T19:29:49.854456Z',
    errorDetail: null,
    documentType: 'resume',
    file: 'http://api.affinda.com/v2/resumes',
  },
  error: { errorCode: null, errorDetail: null },
}
